name = "PowerFlows"
uuid = "94fada2c-fd9a-4e89-8d82-81405f5cb4f6"
authors = ["Jose Daniel Lara <jdlara@berkeley.edu>", "Gabriel Konar-Steenberg <gabriel.konarsteenberg@nrel.gov>", "Roman Bolgaryn <roman.bolgaryn@nrel.gov>"]
version = "0.9.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
InfrastructureSystems = "2cd47ed4-ca9b-11e9-27f2-ab636a7671f1"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
KLU = "ef3ab10e-7fda-4108-b977-705223b18434"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
MUMPS = "55d2b088-9f4e-11e9-26c0-150b02ea6a46"
PowerNetworkMatrices = "bed98974-b02a-5e2f-9fe0-a103f5c450dd"
PowerSystems = "bcd98974-b02a-5e2f-9ee0-a103f5c450dd"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
DataFrames = "1"
DataStructures = "0.18"
Dates = "1"
InfrastructureSystems = "^2.4"
JSON3 = "1"
KLU = "^0.6"
LinearAlgebra = "1"
Logging = "1"
PowerNetworkMatrices = "^0.13"
MPI = "0.20.22"
MPIPreferences = "0.1.11"
MUMPS = "1.5.0"
PowerSystems = "^4.6"
SparseArrays = "1"
julia = "^1.6"
