name = "PowerFlows"
uuid = "94fada2c-fd9a-4e89-8d82-81405f5cb4f6"
authors = ["Jose Daniel Lara <jdlara@berkeley.edu>", "Gabriel Konar-Steenberg <gabriel.konarsteenberg@nrel.gov>", "Roman Bolgaryn <roman.bolgaryn@nrel.gov>"]
version = "0.9.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
InfrastructureSystems = "2cd47ed4-ca9b-11e9-27f2-ab636a7671f1"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
KLU = "ef3ab10e-7fda-4108-b977-705223b18434"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
PowerNetworkMatrices = "bed98974-b02a-5e2f-9fe0-a103f5c450dd"
PowerSystems = "bcd98974-b02a-5e2f-9ee0-a103f5c450dd"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
DataFrames = "1"
DataStructures = "0.19"
Dates = "1"
InfrastructureSystems = "3"
JSON3 = "1"
KLU = "^0.6"
LineSearches = "7.4.0"
LinearAlgebra = "1"
Logging = "1"
PowerNetworkMatrices = "^0.13"
PowerSystems = "5"
SparseArrays = "1"
StaticArrays = "1.9.13"
julia = "^1.6"
